--
-- Copyright (c) 2020 Tim Winchester
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy of
-- this software and associated documentation files (the "Software"), to deal in
-- the Software without restriction, including without limitation the rights to
-- use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
-- of the Software, and to permit persons to whom the Software is furnished to do
-- so, subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in all
-- copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-- SOFTWARE.
--

local KEYS = {}
KEYS.A = 30
KEYS.B = 48
KEYS.C = 46
KEYS.D = 32
KEYS.E = 18
KEYS.F = 33
KEYS.G = 34
KEYS.H = 35
KEYS.I = 23
KEYS.J = 36
KEYS.K = 37
KEYS.L = 38
KEYS.M = 50
KEYS.N = 49
KEYS.O = 24
KEYS.P = 25
KEYS.Q = 16
KEYS.R = 19
KEYS.S = 31
KEYS.T = 20
KEYS.U = 22
KEYS.V = 47
KEYS.W = 17
KEYS.X = 45
KEYS.Y = 21
KEYS.Z = 44

KEYS.ONE = 2
KEYS.TWO = 3
KEYS.THREE = 4
KEYS.FOUR = 5
KEYS.FIVE = 6
KEYS.SIX = 7
KEYS.SEVEN = 8
KEYS.EIGHT = 9
KEYS.NINE = 10
KEYS.ZERO = 11

KEYS.PERIOD = 52
KEYS.PERIOD_NEEDS_SHIFT = false
KEYS.COMMA = 51
KEYS.COMMA_NEEDS_SHIFT = false
KEYS.HYPHEN = 12
KEYS.HYPHEN_NEEDS_SHIFT = false
KEYS.EXCLAMATION_POINT = 2
KEYS.EXCLAMATION_POINT_NEEDS_SHIFT = true
KEYS.SLASH = 8
KEYS.SLASH_NEEDS_SHIFT = true
KEYS.QUESTION_MARK = 53
KEYS.QUESTION_MARK_NEEDS_SHIFT = true
KEYS.SINGLE_QUOTATION_MARK = 40
KEYS.SINGLE_QUOTATION_MARK_NEEDS_SHIFT = false
KEYS.DOUBLE_QUOTATION_MARK = 40
KEYS.DOUBLE_QUOTATION_MARK_NEEDS_SHIFT = true

KEYS.UP_ARROW = 200
KEYS.DOWN_ARROW = 208
KEYS.LEFT_ARROW = 203
KEYS.RIGHT_ARROW = 205

KEYS.BACKSPACE = 14
KEYS.ESCAPE = 1
KEYS.ENTER = 28
KEYS.SPACEBAR = 57
KEYS.TAB = 15
KEYS.CTRL = 29
KEYS.SHIFT = 42
KEYS.HOME = 199
KEYS.END = 207
KEYS.DELETE = 211

return KEYS
